### ISSUE TITLE
Dataset source?

### ISSUE THREAD

**Issue by NamanHS** [AdithyaViswanathan1/Early-Stage-Diabetes-Detection#1]
please give reference link of the source of dataset used in this

**Comment by AdithyaViswanathan1** [comment]
Sorry about that. Here is the link: https://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset.

**Comment by AdithyaViswanathan1** [comment]
[Link to Dataset](https://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset.)

**Comment by NamanHS** [comment]
Thank you!
